### ISSUE TITLE
nilearn missing from requirements.txt

### ISSUE THREAD

**Issue by saigerutherford** [ppsp-team/PyNM#26]
Re: [JOSS review](https://github.com/openjournals/joss-reviews/issues/4321) functionality

When running the tutorials, I get an error in tutorials `5-model_selection.ipynb` and `6-downstream_analysis.ipynb` because nilearn is not installed in the virtual environment. Please add nilearn to `requirements.txt`.

**Comment by harveyaa** [comment]
Hi @saigerutherford, nilearn is only used in that tutorial as a part of example usage of pynm and isn't required for the package itself. In order to keep the package lightweight I added notebook cells to the relevant tutorials with a note about nilearn installation and the code to do so on the spot rather than putting nilearn in the `requirements.txt`.
