### ISSUE TITLE
tutorial 4 error due to R installation

### ISSUE THREAD

**Issue by saigerutherford** [ppsp-team/PyNM#27]
Re: [JOSS review](https://github.com/openjournals/joss-reviews/issues/4321) functionality

I am unable to run the `4-complex_data.ipynb` tutorial because I do not have R installed on my laptop, and there are no clear instructions for this requirement and how to fulfill it. It also reads in the paper as if you have written the GAMLSS R functions in python, which does not seem to be true based on the tutorial errors. Please clarify this in the installation instructions and in the paper.

**Comment by harveyaa** [comment]
Hi @saigerutherford, re R installation instructions: 
I added a link to the documentation for installing R in the `README.md` and state that it is a necessary prerequisite for using the GAMLSS model. This seems fair to me since the installation is system specific and outside of the python package universe it seems out of the scope of the pynm documentation.

re GAMLSS implementation reference in the paper:
The paper reads "...including a wrapper for GAMLSS [@rigby:2005] from R that is otherwise not yet available in python...", which I feel makes it clear the GAMLSS functions are in R and have not been implemented in python (by me or anyone to my knowledge).
